// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tunyosiyebffyumxjbcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1bnlvc2l5ZWJmZnl1bXhqYmNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzgxODUsImV4cCI6MjA3MDY1NDE4NX0.ZNwEvy6CNiB5ON7PNxAANJbP09WCosHGSy-ThduA-mE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});